### ISSUE TITLE
 /authz-info vs. psk_identity "shortcut"

### ISSUE THREAD

**Issue by obgm** [ace-wg/ace-dtls-profile#10]
(Reported bei Jim Schaad):

* how does C know if (a) `POST` to `/authz-info` or the (b) `psk_identity` "shortcut" are supported by RS?
* ACE framework has (a) only
* does this imply that (a) is mandatory?

* options for handling case (b)
      * **b.1:** rely on external knowledge
      * **b.2:** trial-and-error
      * **b.3:** disallow

**Comment by LudwigSeitz** [comment]
Regarding the 3rd bullet. Yes (a) is MTI. As for the 4th bullet I've implemented variant b.2, we could however consider defining additional parameters that the AS returns to the client in addition to the profile identifier.

**Comment by obgm** [comment]
Closed by commits  2ae51c1 and 317f9f7.
