### ISSUE TITLE
What to do when the last valid token has expired?

### ISSUE THREAD

**Issue by obgm** [ace-wg/ace-dtls-profile#12]
(Reported bei Jim Schaad):

“no valid access token” covers three cases:

1. expired access token,
2. no token (but required for protected resource), and
3. rogue token.

* Tear down DTLS session (= `MUST`)?
    * pro: clear state early
    * con: reversing roles?

**Comment by LudwigSeitz** [comment]
Shouldn't we give the client a chance to POST a new token to /authz-info? Tearing down the DTLS session just because a token has expired seems pretty resource-wasteful to me.

**Comment by obgm** [comment]
Closed by commit 923fa97.
