### ISSUE TITLE
Re-use kid parameter from CWT POP?

### ISSUE THREAD

**Issue by obgm** [ace-wg/ace-dtls-profile#17]
@jimsch has raised the question whether the `kid` parameter in Section 2.3 (Token Expiration) needs to be defined given that it is already defined in
[CWT POP](https://tools.ietf.org/html/draft-ietf-ace-cwt-proof-of-possession-03).

The issue here is that this would need to be within a `cnf`claim to avoid number collisions.

**Comment by LudwigSeitz** [comment]
Move the definition to the ACE framework.
