### ISSUE TITLE
Need to define a new cnf-level for transferring key derivation parameters 

### ISSUE THREAD

**Issue by obgm** [ace-wg/ace-dtls-profile#22]
Commit 90f1fb8 introduces a new `cnf`-parameter called `ACE_Salt` which is neither defined in the DTLS profile document nor in [RFC 8152](https://tools.ietf.org/html/rfc8152) nor in the ACE framework document. The parameter therefore needs to be defined somewhere but deems to be more generic than DTLS-profile only.

**Comment by LudwigSeitz** [comment]
Göran agreed to have a look at this yesterday.

**Comment by gselander** [comment]
No new data structure is needed, the salt can be transported in ´kid´. Resolved in 7b72706.
