### ISSUE TITLE
Define the CBOR abbreviations used

### ISSUE THREAD

**Issue by LudwigSeitz** [ace-wg/ace-dtls-profile#8]
The document currently uses uint 0 as abbreviation for "AS" and uint 5 as abbreviation for "nonce". As far as I can see these are only implicitly defined in the example figure. We should define them explicitly.

**Comment by jimsch** [comment]
@LudwigSeitz  - Is this not in the main document now - should have no additional CBOR abbreviations here that I know of.

**Comment by LudwigSeitz** [comment]
This got moved into the framework. Closing.
