### ISSUE TITLE
Do we want to send AS information for every type of error?

### ISSUE THREAD

**Issue by LudwigSeitz** [ace-wg/ace-dtls-profile#9]
As the draft is currently written (or as I interpret it) every access control failure (4.01, 4.03 and 4.05) renders a response containing the AS information. Do we really need to do this for the 4.03 and 4.05 cases?

**Comment by jimsch** [comment]
@LudwigSeitz - should be in the main document no the profile.

**Comment by LudwigSeitz** [comment]
Correct, that was moved.
